// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/pkg/apis/capability/v1/capability.proto

package v1

import (
	_ "github.com/kralicky/codegen/cli"
	_ "github.com/kralicky/totem"
	v1 "github.com/rancher/opni/pkg/apis/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallResponseStatus int32

const (
	InstallResponseStatus_Unknown InstallResponseStatus = 0
	InstallResponseStatus_Success InstallResponseStatus = 1
	InstallResponseStatus_Warning InstallResponseStatus = 2
	InstallResponseStatus_Error   InstallResponseStatus = 3
)

// Enum value maps for InstallResponseStatus.
var (
	InstallResponseStatus_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Warning",
		3: "Error",
	}
	InstallResponseStatus_value = map[string]int32{
		"Unknown": 0,
		"Success": 1,
		"Warning": 2,
		"Error":   3,
	}
)

func (x InstallResponseStatus) Enum() *InstallResponseStatus {
	p := new(InstallResponseStatus)
	*p = x
	return p
}

func (x InstallResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_enumTypes[0].Descriptor()
}

func (InstallResponseStatus) Type() protoreflect.EnumType {
	return &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_enumTypes[0]
}

func (x InstallResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallResponseStatus.Descriptor instead.
func (InstallResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{0}
}

type Details struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source           string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	AvailableDrivers []string               `protobuf:"bytes,3,rep,name=availableDrivers,proto3" json:"availableDrivers,omitempty"`
	EnabledDriver    string                 `protobuf:"bytes,4,opt,name=enabledDriver,proto3" json:"enabledDriver,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *Details) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Details) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Details) GetAvailableDrivers() []string {
	if x != nil {
		return x.AvailableDrivers
	}
	return nil
}

func (x *Details) GetEnabledDriver() string {
	if x != nil {
		return x.EnabledDriver
	}
	return ""
}

type Filter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CapabilityNames []string               `protobuf:"bytes,1,rep,name=capabilityNames,proto3" json:"capabilityNames,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetCapabilityNames() []string {
	if x != nil {
		return x.CapabilityNames
	}
	return nil
}

type InstallRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Capability     *v1.Reference          `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Agent          *v1.Reference          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	IgnoreWarnings bool                   `protobuf:"varint,2,opt,name=ignoreWarnings,proto3" json:"ignoreWarnings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{2}
}

func (x *InstallRequest) GetCapability() *v1.Reference {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *InstallRequest) GetAgent() *v1.Reference {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *InstallRequest) GetIgnoreWarnings() bool {
	if x != nil {
		return x.IgnoreWarnings
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *v1.Reference          `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Agent         *v1.Reference          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetCapability() *v1.Reference {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *StatusRequest) GetAgent() *v1.Reference {
	if x != nil {
		return x.Agent
	}
	return nil
}

type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        InstallResponseStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=capability.InstallResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{4}
}

func (x *InstallResponse) GetStatus() InstallResponseStatus {
	if x != nil {
		return x.Status
	}
	return InstallResponseStatus_Unknown
}

func (x *InstallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UninstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *v1.Reference          `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Agent         *v1.Reference          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallRequest) Reset() {
	*x = UninstallRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallRequest) ProtoMessage() {}

func (x *UninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallRequest.ProtoReflect.Descriptor instead.
func (*UninstallRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{5}
}

func (x *UninstallRequest) GetCapability() *v1.Reference {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *UninstallRequest) GetAgent() *v1.Reference {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *UninstallRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type InstallerTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallerTemplateResponse) Reset() {
	*x = InstallerTemplateResponse{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallerTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerTemplateResponse) ProtoMessage() {}

func (x *InstallerTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerTemplateResponse.ProtoReflect.Descriptor instead.
func (*InstallerTemplateResponse) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{6}
}

func (x *InstallerTemplateResponse) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

type NodeCapabilityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastSync      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastSync,proto3" json:"lastSync,omitempty"`
	Conditions    []string               `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	LastRevision  *v1.Revision           `protobuf:"bytes,4,opt,name=lastRevision,proto3" json:"lastRevision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilityStatus) Reset() {
	*x = NodeCapabilityStatus{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilityStatus) ProtoMessage() {}

func (x *NodeCapabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilityStatus.ProtoReflect.Descriptor instead.
func (*NodeCapabilityStatus) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{7}
}

func (x *NodeCapabilityStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NodeCapabilityStatus) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

func (x *NodeCapabilityStatus) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *NodeCapabilityStatus) GetLastRevision() *v1.Revision {
	if x != nil {
		return x.LastRevision
	}
	return nil
}

type UninstallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *v1.Reference          `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Agent         *v1.Reference          `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallStatusRequest) Reset() {
	*x = UninstallStatusRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallStatusRequest) ProtoMessage() {}

func (x *UninstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallStatusRequest.ProtoReflect.Descriptor instead.
func (*UninstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{8}
}

func (x *UninstallStatusRequest) GetCapability() *v1.Reference {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *UninstallStatusRequest) GetAgent() *v1.Reference {
	if x != nil {
		return x.Agent
	}
	return nil
}

type CancelUninstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *v1.Reference          `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Agent         *v1.Reference          `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUninstallRequest) Reset() {
	*x = CancelUninstallRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUninstallRequest) ProtoMessage() {}

func (x *CancelUninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUninstallRequest.ProtoReflect.Descriptor instead.
func (*CancelUninstallRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{9}
}

func (x *CancelUninstallRequest) GetCapability() *v1.Reference {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *CancelUninstallRequest) GetAgent() *v1.Reference {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DetailsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Details             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	LastRevision  *v1.Revision           `protobuf:"bytes,4,opt,name=lastRevision,proto3" json:"lastRevision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsList) Reset() {
	*x = DetailsList{}
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsList) ProtoMessage() {}

func (x *DetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsList.ProtoReflect.Descriptor instead.
func (*DetailsList) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP(), []int{10}
}

func (x *DetailsList) GetItems() []*Details {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DetailsList) GetLastRevision() *v1.Revision {
	if x != nil {
		return x.LastRevision
	}
	return nil
}

var File_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDesc = "" +
	"\n" +
	"?github.com/rancher/opni/pkg/apis/capability/v1/capability.proto\x12\n" +
	"capability\x1a)github.com/kralicky/codegen/cli/cli.proto\x1a*github.com/kralicky/totem/extensions.proto\x1a3github.com/rancher/opni/pkg/apis/core/v1/core.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\aDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12*\n" +
	"\x10availableDrivers\x18\x03 \x03(\tR\x10availableDrivers\x12$\n" +
	"\renabledDriver\x18\x04 \x01(\tR\renabledDriver\"2\n" +
	"\x06Filter\x12(\n" +
	"\x0fcapabilityNames\x18\x01 \x03(\tR\x0fcapabilityNames\"\x90\x01\n" +
	"\x0eInstallRequest\x12/\n" +
	"\n" +
	"capability\x18\x03 \x01(\v2\x0f.core.ReferenceR\n" +
	"capability\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.core.ReferenceR\x05agent\x12&\n" +
	"\x0eignoreWarnings\x18\x02 \x01(\bR\x0eignoreWarnings\"g\n" +
	"\rStatusRequest\x12/\n" +
	"\n" +
	"capability\x18\x03 \x01(\v2\x0f.core.ReferenceR\n" +
	"capability\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.core.ReferenceR\x05agent\"f\n" +
	"\x0fInstallResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.capability.InstallResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x10UninstallRequest\x12/\n" +
	"\n" +
	"capability\x18\x03 \x01(\v2\x0f.core.ReferenceR\n" +
	"capability\x12%\n" +
	"\x05agent\x18\x01 \x01(\v2\x0f.core.ReferenceR\x05agent\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x06\x8a\xc0\f\x02(\x01R\aoptions\"7\n" +
	"\x19InstallerTemplateResponse\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\"\xbc\x01\n" +
	"\x14NodeCapabilityStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x126\n" +
	"\blastSync\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\x12\x1e\n" +
	"\n" +
	"conditions\x18\x03 \x03(\tR\n" +
	"conditions\x122\n" +
	"\flastRevision\x18\x04 \x01(\v2\x0e.core.RevisionR\flastRevision\"p\n" +
	"\x16UninstallStatusRequest\x12/\n" +
	"\n" +
	"capability\x18\x01 \x01(\v2\x0f.core.ReferenceR\n" +
	"capability\x12%\n" +
	"\x05agent\x18\x02 \x01(\v2\x0f.core.ReferenceR\x05agent\"p\n" +
	"\x16CancelUninstallRequest\x12/\n" +
	"\n" +
	"capability\x18\x01 \x01(\v2\x0f.core.ReferenceR\n" +
	"capability\x12%\n" +
	"\x05agent\x18\x02 \x01(\v2\x0f.core.ReferenceR\x05agent\"l\n" +
	"\vDetailsList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.capability.DetailsR\x05items\x122\n" +
	"\flastRevision\x18\x04 \x01(\v2\x0e.core.RevisionR\flastRevision*I\n" +
	"\x15InstallResponseStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\v\n" +
	"\aWarning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xd6\x03\n" +
	"\aBackend\x12,\n" +
	"\x04Info\x12\x0f.core.Reference\x1a\x13.capability.Details\x127\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x17.capability.DetailsList\x12B\n" +
	"\aInstall\x12\x1a.capability.InstallRequest\x1a\x1b.capability.InstallResponse\x12E\n" +
	"\x06Status\x12\x19.capability.StatusRequest\x1a .capability.NodeCapabilityStatus\x12A\n" +
	"\tUninstall\x12\x1c.capability.UninstallRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0fUninstallStatus\x12\".capability.UninstallStatusRequest\x1a\x10.core.TaskStatus\x12M\n" +
	"\x0fCancelUninstall\x12\".capability.CancelUninstallRequest\x1a\x16.google.protobuf.Empty2E\n" +
	"\x04Node\x12=\n" +
	"\aSyncNow\x12\x12.capability.Filter\x1a\x16.google.protobuf.Empty\"\x06\x8a\xf1\x04\x02\b\x012\xbb\x03\n" +
	"\vRBACManager\x12,\n" +
	"\x04Info\x12\x0f.core.Reference\x1a\x13.capability.Details\x127\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x17.capability.DetailsList\x12M\n" +
	"\x17GetAvailablePermissions\x12\x16.google.protobuf.Empty\x1a\x1a.core.AvailablePermissions\x12&\n" +
	"\aGetRole\x12\x0f.core.Reference\x1a\n" +
	".core.Role\x120\n" +
	"\n" +
	"CreateRole\x12\n" +
	".core.Role\x1a\x16.google.protobuf.Empty\x120\n" +
	"\n" +
	"UpdateRole\x12\n" +
	".core.Role\x1a\x16.google.protobuf.Empty\x125\n" +
	"\n" +
	"DeleteRole\x12\x0f.core.Reference\x1a\x16.google.protobuf.Empty\x123\n" +
	"\tListRoles\x12\x16.google.protobuf.Empty\x1a\x0e.core.RoleListB6\x82\xc0\f\x02\b\x01Z.github.com/rancher/opni/pkg/apis/capability/v1b\x06proto3"

var (
	file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescData []byte
)

func file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDescData
}

var file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_goTypes = []any{
	(InstallResponseStatus)(0),        // 0: capability.InstallResponseStatus
	(*Details)(nil),                   // 1: capability.Details
	(*Filter)(nil),                    // 2: capability.Filter
	(*InstallRequest)(nil),            // 3: capability.InstallRequest
	(*StatusRequest)(nil),             // 4: capability.StatusRequest
	(*InstallResponse)(nil),           // 5: capability.InstallResponse
	(*UninstallRequest)(nil),          // 6: capability.UninstallRequest
	(*InstallerTemplateResponse)(nil), // 7: capability.InstallerTemplateResponse
	(*NodeCapabilityStatus)(nil),      // 8: capability.NodeCapabilityStatus
	(*UninstallStatusRequest)(nil),    // 9: capability.UninstallStatusRequest
	(*CancelUninstallRequest)(nil),    // 10: capability.CancelUninstallRequest
	(*DetailsList)(nil),               // 11: capability.DetailsList
	(*v1.Reference)(nil),              // 12: core.Reference
	(*structpb.Struct)(nil),           // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*v1.Revision)(nil),               // 15: core.Revision
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
	(*v1.Role)(nil),                   // 17: core.Role
	(*v1.TaskStatus)(nil),             // 18: core.TaskStatus
	(*v1.AvailablePermissions)(nil),   // 19: core.AvailablePermissions
	(*v1.RoleList)(nil),               // 20: core.RoleList
}
var file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_depIdxs = []int32{
	12, // 0: capability.InstallRequest.capability:type_name -> core.Reference
	12, // 1: capability.InstallRequest.agent:type_name -> core.Reference
	12, // 2: capability.StatusRequest.capability:type_name -> core.Reference
	12, // 3: capability.StatusRequest.agent:type_name -> core.Reference
	0,  // 4: capability.InstallResponse.status:type_name -> capability.InstallResponseStatus
	12, // 5: capability.UninstallRequest.capability:type_name -> core.Reference
	12, // 6: capability.UninstallRequest.agent:type_name -> core.Reference
	13, // 7: capability.UninstallRequest.options:type_name -> google.protobuf.Struct
	14, // 8: capability.NodeCapabilityStatus.lastSync:type_name -> google.protobuf.Timestamp
	15, // 9: capability.NodeCapabilityStatus.lastRevision:type_name -> core.Revision
	12, // 10: capability.UninstallStatusRequest.capability:type_name -> core.Reference
	12, // 11: capability.UninstallStatusRequest.agent:type_name -> core.Reference
	12, // 12: capability.CancelUninstallRequest.capability:type_name -> core.Reference
	12, // 13: capability.CancelUninstallRequest.agent:type_name -> core.Reference
	1,  // 14: capability.DetailsList.items:type_name -> capability.Details
	15, // 15: capability.DetailsList.lastRevision:type_name -> core.Revision
	12, // 16: capability.Backend.Info:input_type -> core.Reference
	16, // 17: capability.Backend.List:input_type -> google.protobuf.Empty
	3,  // 18: capability.Backend.Install:input_type -> capability.InstallRequest
	4,  // 19: capability.Backend.Status:input_type -> capability.StatusRequest
	6,  // 20: capability.Backend.Uninstall:input_type -> capability.UninstallRequest
	9,  // 21: capability.Backend.UninstallStatus:input_type -> capability.UninstallStatusRequest
	10, // 22: capability.Backend.CancelUninstall:input_type -> capability.CancelUninstallRequest
	2,  // 23: capability.Node.SyncNow:input_type -> capability.Filter
	12, // 24: capability.RBACManager.Info:input_type -> core.Reference
	16, // 25: capability.RBACManager.List:input_type -> google.protobuf.Empty
	16, // 26: capability.RBACManager.GetAvailablePermissions:input_type -> google.protobuf.Empty
	12, // 27: capability.RBACManager.GetRole:input_type -> core.Reference
	17, // 28: capability.RBACManager.CreateRole:input_type -> core.Role
	17, // 29: capability.RBACManager.UpdateRole:input_type -> core.Role
	12, // 30: capability.RBACManager.DeleteRole:input_type -> core.Reference
	16, // 31: capability.RBACManager.ListRoles:input_type -> google.protobuf.Empty
	1,  // 32: capability.Backend.Info:output_type -> capability.Details
	11, // 33: capability.Backend.List:output_type -> capability.DetailsList
	5,  // 34: capability.Backend.Install:output_type -> capability.InstallResponse
	8,  // 35: capability.Backend.Status:output_type -> capability.NodeCapabilityStatus
	16, // 36: capability.Backend.Uninstall:output_type -> google.protobuf.Empty
	18, // 37: capability.Backend.UninstallStatus:output_type -> core.TaskStatus
	16, // 38: capability.Backend.CancelUninstall:output_type -> google.protobuf.Empty
	16, // 39: capability.Node.SyncNow:output_type -> google.protobuf.Empty
	1,  // 40: capability.RBACManager.Info:output_type -> capability.Details
	11, // 41: capability.RBACManager.List:output_type -> capability.DetailsList
	19, // 42: capability.RBACManager.GetAvailablePermissions:output_type -> core.AvailablePermissions
	17, // 43: capability.RBACManager.GetRole:output_type -> core.Role
	16, // 44: capability.RBACManager.CreateRole:output_type -> google.protobuf.Empty
	16, // 45: capability.RBACManager.UpdateRole:output_type -> google.protobuf.Empty
	16, // 46: capability.RBACManager.DeleteRole:output_type -> google.protobuf.Empty
	20, // 47: capability.RBACManager.ListRoles:output_type -> core.RoleList
	32, // [32:48] is the sub-list for method output_type
	16, // [16:32] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_init() }
func file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_init() {
	if File_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_depIdxs,
		EnumInfos:         file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_enumTypes,
		MessageInfos:      file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto = out.File
	file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_goTypes = nil
	file_github_com_rancher_opni_pkg_apis_capability_v1_capability_proto_depIdxs = nil
}
