// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: github.com/rancher/opni/pkg/apis/proxy/v1/proxy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegisterProxy_Backend_FullMethodName     = "/proxy.RegisterProxy/Backend"
	RegisterProxy_Path_FullMethodName        = "/proxy.RegisterProxy/Path"
	RegisterProxy_AuthHeaders_FullMethodName = "/proxy.RegisterProxy/AuthHeaders"
)

// RegisterProxyClient is the client API for RegisterProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterProxyClient interface {
	Backend(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BackendInfo, error)
	Path(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PathInfo, error)
	AuthHeaders(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error)
}

type registerProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterProxyClient(cc grpc.ClientConnInterface) RegisterProxyClient {
	return &registerProxyClient{cc}
}

func (c *registerProxyClient) Backend(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BackendInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackendInfo)
	err := c.cc.Invoke(ctx, RegisterProxy_Backend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerProxyClient) Path(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PathInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathInfo)
	err := c.cc.Invoke(ctx, RegisterProxy_Path_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerProxyClient) AuthHeaders(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeaderResponse)
	err := c.cc.Invoke(ctx, RegisterProxy_AuthHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterProxyServer is the server API for RegisterProxy service.
// All implementations should embed UnimplementedRegisterProxyServer
// for forward compatibility.
type RegisterProxyServer interface {
	Backend(context.Context, *emptypb.Empty) (*BackendInfo, error)
	Path(context.Context, *emptypb.Empty) (*PathInfo, error)
	AuthHeaders(context.Context, *HeaderRequest) (*HeaderResponse, error)
}

// UnimplementedRegisterProxyServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterProxyServer struct{}

func (UnimplementedRegisterProxyServer) Backend(context.Context, *emptypb.Empty) (*BackendInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Backend not implemented")
}
func (UnimplementedRegisterProxyServer) Path(context.Context, *emptypb.Empty) (*PathInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Path not implemented")
}
func (UnimplementedRegisterProxyServer) AuthHeaders(context.Context, *HeaderRequest) (*HeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthHeaders not implemented")
}
func (UnimplementedRegisterProxyServer) testEmbeddedByValue() {}

// UnsafeRegisterProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterProxyServer will
// result in compilation errors.
type UnsafeRegisterProxyServer interface {
	mustEmbedUnimplementedRegisterProxyServer()
}

func RegisterRegisterProxyServer(s grpc.ServiceRegistrar, srv RegisterProxyServer) {
	// If the following call panics, it indicates UnimplementedRegisterProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterProxy_ServiceDesc, srv)
}

func _RegisterProxy_Backend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterProxyServer).Backend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterProxy_Backend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterProxyServer).Backend(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterProxy_Path_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterProxyServer).Path(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterProxy_Path_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterProxyServer).Path(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterProxy_AuthHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterProxyServer).AuthHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterProxy_AuthHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterProxyServer).AuthHeaders(ctx, req.(*HeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterProxy_ServiceDesc is the grpc.ServiceDesc for RegisterProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.RegisterProxy",
	HandlerType: (*RegisterProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backend",
			Handler:    _RegisterProxy_Backend_Handler,
		},
		{
			MethodName: "Path",
			Handler:    _RegisterProxy_Path_Handler,
		},
		{
			MethodName: "AuthHeaders",
			Handler:    _RegisterProxy_AuthHeaders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/rancher/opni/pkg/apis/proxy/v1/proxy.proto",
}
