// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/plugins/topology/apis/stream/stream.proto

package stream

import (
	v1 "github.com/rancher/opni/pkg/apis/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphRepr int32

const (
	GraphRepr_None         GraphRepr = 0
	GraphRepr_KubectlGraph GraphRepr = 1
)

// Enum value maps for GraphRepr.
var (
	GraphRepr_name = map[int32]string{
		0: "None",
		1: "KubectlGraph",
	}
	GraphRepr_value = map[string]int32{
		"None":         0,
		"KubectlGraph": 1,
	}
)

func (x GraphRepr) Enum() *GraphRepr {
	p := new(GraphRepr)
	*p = x
	return p
}

func (x GraphRepr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphRepr) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_enumTypes[0].Descriptor()
}

func (GraphRepr) Type() protoreflect.EnumType {
	return &file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_enumTypes[0]
}

func (x GraphRepr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphRepr.Descriptor instead.
func (GraphRepr) EnumDescriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescGZIP(), []int{0}
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *TopologyGraph         `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetGraph() *TopologyGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

// FIXME: copied from orchestrator.proto due to duplicate symbol bug
type TopologyGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     *v1.Reference          `protobuf:"bytes,1,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Repr          GraphRepr              `protobuf:"varint,3,opt,name=repr,proto3,enum=stream.topology.GraphRepr" json:"repr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyGraph) Reset() {
	*x = TopologyGraph{}
	mi := &file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyGraph) ProtoMessage() {}

func (x *TopologyGraph) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyGraph.ProtoReflect.Descriptor instead.
func (*TopologyGraph) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *TopologyGraph) GetClusterId() *v1.Reference {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

func (x *TopologyGraph) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TopologyGraph) GetRepr() GraphRepr {
	if x != nil {
		return x.Repr
	}
	return GraphRepr_None
}

var File_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDesc = "" +
	"\n" +
	"Agithub.com/rancher/opni/plugins/topology/apis/stream/stream.proto\x12\x0fstream.topology\x1a\x1bgoogle/protobuf/empty.proto\x1a3github.com/rancher/opni/pkg/apis/core/v1/core.proto\"?\n" +
	"\aPayload\x124\n" +
	"\x05graph\x18\x01 \x01(\v2\x1e.stream.topology.TopologyGraphR\x05graph\"\x82\x01\n" +
	"\rTopologyGraph\x12-\n" +
	"\tclusterId\x18\x01 \x01(\v2\x0f.core.ReferenceR\tclusterId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12.\n" +
	"\x04repr\x18\x03 \x01(\x0e2\x1a.stream.topology.GraphReprR\x04repr*'\n" +
	"\tGraphRepr\x12\b\n" +
	"\x04None\x10\x00\x12\x10\n" +
	"\fKubectlGraph\x10\x012\x8c\x01\n" +
	"\x0eRemoteTopology\x128\n" +
	"\x04Push\x12\x18.stream.topology.Payload\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\fSyncTopology\x12\x18.stream.topology.Payload\x1a\x16.google.protobuf.EmptyB6Z4github.com/rancher/opni/plugins/topology/apis/streamb\x06proto3"

var (
	file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescData []byte
)

func file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDescData
}

var file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_goTypes = []any{
	(GraphRepr)(0),        // 0: stream.topology.GraphRepr
	(*Payload)(nil),       // 1: stream.topology.Payload
	(*TopologyGraph)(nil), // 2: stream.topology.TopologyGraph
	(*v1.Reference)(nil),  // 3: core.Reference
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_depIdxs = []int32{
	2, // 0: stream.topology.Payload.graph:type_name -> stream.topology.TopologyGraph
	3, // 1: stream.topology.TopologyGraph.clusterId:type_name -> core.Reference
	0, // 2: stream.topology.TopologyGraph.repr:type_name -> stream.topology.GraphRepr
	1, // 3: stream.topology.RemoteTopology.Push:input_type -> stream.topology.Payload
	1, // 4: stream.topology.RemoteTopology.SyncTopology:input_type -> stream.topology.Payload
	4, // 5: stream.topology.RemoteTopology.Push:output_type -> google.protobuf.Empty
	4, // 6: stream.topology.RemoteTopology.SyncTopology:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_init() }
func file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_init() {
	if File_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_depIdxs,
		EnumInfos:         file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_enumTypes,
		MessageInfos:      file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto = out.File
	file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_goTypes = nil
	file_github_com_rancher_opni_plugins_topology_apis_stream_stream_proto_depIdxs = nil
}
