// Code generated by internal/codegen. You may edit parts of this file.
// Field numbers and custom options will be preserved for matching field names.
// All other modifications will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/internal/cortex/config/runtimeconfig/runtimeconfig.proto

package runtimeconfig

import (
	_ "github.com/kralicky/codegen/cli"
	validation "github.com/rancher/opni/internal/cortex/config/validation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeConfigValues struct {
	state                               protoimpl.MessageState        `protogen:"open.v1"`
	Overrides                           map[string]*validation.Limits `protobuf:"bytes,1,rep,name=overrides,proto3" json:"overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MultiKvConfig                       *KvMultiRuntimeConfig         `protobuf:"bytes,2,opt,name=multi_kv_config,json=multiKvConfig,proto3" json:"multi_kv_config,omitempty"`
	IngesterStreamChunksWhenUsingBlocks *bool                         `protobuf:"varint,3,opt,name=ingester_stream_chunks_when_using_blocks,json=ingesterStreamChunksWhenUsingBlocks,proto3,oneof" json:"ingester_stream_chunks_when_using_blocks,omitempty"`
	IngesterLimits                      *IngesterInstanceLimits       `protobuf:"bytes,4,opt,name=ingester_limits,json=ingesterLimits,proto3" json:"ingester_limits,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *RuntimeConfigValues) Reset() {
	*x = RuntimeConfigValues{}
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeConfigValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfigValues) ProtoMessage() {}

func (x *RuntimeConfigValues) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfigValues.ProtoReflect.Descriptor instead.
func (*RuntimeConfigValues) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeConfigValues) GetOverrides() map[string]*validation.Limits {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *RuntimeConfigValues) GetMultiKvConfig() *KvMultiRuntimeConfig {
	if x != nil {
		return x.MultiKvConfig
	}
	return nil
}

func (x *RuntimeConfigValues) GetIngesterStreamChunksWhenUsingBlocks() bool {
	if x != nil && x.IngesterStreamChunksWhenUsingBlocks != nil {
		return *x.IngesterStreamChunksWhenUsingBlocks
	}
	return false
}

func (x *RuntimeConfigValues) GetIngesterLimits() *IngesterInstanceLimits {
	if x != nil {
		return x.IngesterLimits
	}
	return nil
}

type IngesterInstanceLimits struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MaxIngestionRate         *float64               `protobuf:"fixed64,1,opt,name=max_ingestion_rate,json=maxIngestionRate,proto3,oneof" json:"max_ingestion_rate,omitempty"`
	MaxTenants               *int64                 `protobuf:"varint,2,opt,name=max_tenants,json=maxTenants,proto3,oneof" json:"max_tenants,omitempty"`
	MaxSeries                *int64                 `protobuf:"varint,3,opt,name=max_series,json=maxSeries,proto3,oneof" json:"max_series,omitempty"`
	MaxInflightPushRequests  *int64                 `protobuf:"varint,4,opt,name=max_inflight_push_requests,json=maxInflightPushRequests,proto3,oneof" json:"max_inflight_push_requests,omitempty"`
	MaxInflightQueryRequests *int64                 `protobuf:"varint,5,opt,name=max_inflight_query_requests,json=maxInflightQueryRequests,proto3,oneof" json:"max_inflight_query_requests,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *IngesterInstanceLimits) Reset() {
	*x = IngesterInstanceLimits{}
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngesterInstanceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngesterInstanceLimits) ProtoMessage() {}

func (x *IngesterInstanceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngesterInstanceLimits.ProtoReflect.Descriptor instead.
func (*IngesterInstanceLimits) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescGZIP(), []int{1}
}

func (x *IngesterInstanceLimits) GetMaxIngestionRate() float64 {
	if x != nil && x.MaxIngestionRate != nil {
		return *x.MaxIngestionRate
	}
	return 0
}

func (x *IngesterInstanceLimits) GetMaxTenants() int64 {
	if x != nil && x.MaxTenants != nil {
		return *x.MaxTenants
	}
	return 0
}

func (x *IngesterInstanceLimits) GetMaxSeries() int64 {
	if x != nil && x.MaxSeries != nil {
		return *x.MaxSeries
	}
	return 0
}

func (x *IngesterInstanceLimits) GetMaxInflightPushRequests() int64 {
	if x != nil && x.MaxInflightPushRequests != nil {
		return *x.MaxInflightPushRequests
	}
	return 0
}

func (x *IngesterInstanceLimits) GetMaxInflightQueryRequests() int64 {
	if x != nil && x.MaxInflightQueryRequests != nil {
		return *x.MaxInflightQueryRequests
	}
	return 0
}

type KvMultiRuntimeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       *string                `protobuf:"bytes,1,opt,name=primary,proto3,oneof" json:"primary,omitempty"`
	MirrorEnabled *bool                  `protobuf:"varint,2,opt,name=mirror_enabled,json=mirrorEnabled,proto3,oneof" json:"mirror_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvMultiRuntimeConfig) Reset() {
	*x = KvMultiRuntimeConfig{}
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvMultiRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvMultiRuntimeConfig) ProtoMessage() {}

func (x *KvMultiRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvMultiRuntimeConfig.ProtoReflect.Descriptor instead.
func (*KvMultiRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescGZIP(), []int{2}
}

func (x *KvMultiRuntimeConfig) GetPrimary() string {
	if x != nil && x.Primary != nil {
		return *x.Primary
	}
	return ""
}

func (x *KvMultiRuntimeConfig) GetMirrorEnabled() bool {
	if x != nil && x.MirrorEnabled != nil {
		return *x.MirrorEnabled
	}
	return false
}

var File_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/rancher/opni/internal/cortex/config/runtimeconfig/runtimeconfig.proto\x12\rruntimeconfig\x1a)github.com/kralicky/codegen/cli/cli.proto\x1aFgithub.com/rancher/opni/internal/cortex/config/validation/limits.proto\"\xe6\x03\n" +
	"\x13RuntimeConfigValues\x12W\n" +
	"\toverrides\x18\x01 \x03(\v21.runtimeconfig.RuntimeConfigValues.OverridesEntryB\x06\x8a\xc0\f\x02(\x01R\toverrides\x12K\n" +
	"\x0fmulti_kv_config\x18\x02 \x01(\v2#.runtimeconfig.KvMultiRuntimeConfigR\rmultiKvConfig\x12Z\n" +
	"(ingester_stream_chunks_when_using_blocks\x18\x03 \x01(\bH\x00R#ingesterStreamChunksWhenUsingBlocks\x88\x01\x01\x12N\n" +
	"\x0fingester_limits\x18\x04 \x01(\v2%.runtimeconfig.IngesterInstanceLimitsR\x0eingesterLimits\x1aP\n" +
	"\x0eOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.validation.LimitsR\x05value:\x028\x01B+\n" +
	")_ingester_stream_chunks_when_using_blocks\"\x90\x03\n" +
	"\x16IngesterInstanceLimits\x121\n" +
	"\x12max_ingestion_rate\x18\x01 \x01(\x01H\x00R\x10maxIngestionRate\x88\x01\x01\x12$\n" +
	"\vmax_tenants\x18\x02 \x01(\x03H\x01R\n" +
	"maxTenants\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_series\x18\x03 \x01(\x03H\x02R\tmaxSeries\x88\x01\x01\x12@\n" +
	"\x1amax_inflight_push_requests\x18\x04 \x01(\x03H\x03R\x17maxInflightPushRequests\x88\x01\x01\x12B\n" +
	"\x1bmax_inflight_query_requests\x18\x05 \x01(\x03H\x04R\x18maxInflightQueryRequests\x88\x01\x01B\x15\n" +
	"\x13_max_ingestion_rateB\x0e\n" +
	"\f_max_tenantsB\r\n" +
	"\v_max_seriesB\x1d\n" +
	"\x1b_max_inflight_push_requestsB\x1e\n" +
	"\x1c_max_inflight_query_requests\"\x80\x01\n" +
	"\x14KvMultiRuntimeConfig\x12\x1d\n" +
	"\aprimary\x18\x01 \x01(\tH\x00R\aprimary\x88\x01\x01\x12*\n" +
	"\x0emirror_enabled\x18\x02 \x01(\bH\x01R\rmirrorEnabled\x88\x01\x01B\n" +
	"\n" +
	"\b_primaryB\x11\n" +
	"\x0f_mirror_enabledBF\x82\xc0\f\x04\b\x01\x10\x01Z<github.com/rancher/opni/internal/cortex/config/runtimeconfigb\x06proto3"

var (
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescData []byte
)

func file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDesc), len(file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDescData
}

var file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_goTypes = []any{
	(*RuntimeConfigValues)(nil),    // 0: runtimeconfig.RuntimeConfigValues
	(*IngesterInstanceLimits)(nil), // 1: runtimeconfig.IngesterInstanceLimits
	(*KvMultiRuntimeConfig)(nil),   // 2: runtimeconfig.KvMultiRuntimeConfig
	nil,                            // 3: runtimeconfig.RuntimeConfigValues.OverridesEntry
	(*validation.Limits)(nil),      // 4: validation.Limits
}
var file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_depIdxs = []int32{
	3, // 0: runtimeconfig.RuntimeConfigValues.overrides:type_name -> runtimeconfig.RuntimeConfigValues.OverridesEntry
	2, // 1: runtimeconfig.RuntimeConfigValues.multi_kv_config:type_name -> runtimeconfig.KvMultiRuntimeConfig
	1, // 2: runtimeconfig.RuntimeConfigValues.ingester_limits:type_name -> runtimeconfig.IngesterInstanceLimits
	4, // 3: runtimeconfig.RuntimeConfigValues.OverridesEntry.value:type_name -> validation.Limits
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_init()
}
func file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_init() {
	if File_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto != nil {
		return
	}
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[0].OneofWrappers = []any{}
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[1].OneofWrappers = []any{}
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDesc), len(file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto = out.File
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_goTypes = nil
	file_github_com_rancher_opni_internal_cortex_config_runtimeconfig_runtimeconfig_proto_depIdxs = nil
}
