// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/plugins/topology/apis/orchestrator/orchestrator.proto

package orchestrator

import (
	_ "github.com/rancher/opni/pkg/apis/core/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallState int32

const (
	InstallState_Unknown      InstallState = 0
	InstallState_NotInstalled InstallState = 1
	InstallState_Updating     InstallState = 2
	InstallState_Installed    InstallState = 3
	InstallState_Uninstalling InstallState = 4
)

// Enum value maps for InstallState.
var (
	InstallState_name = map[int32]string{
		0: "Unknown",
		1: "NotInstalled",
		2: "Updating",
		3: "Installed",
		4: "Uninstalling",
	}
	InstallState_value = map[string]int32{
		"Unknown":      0,
		"NotInstalled": 1,
		"Updating":     2,
		"Installed":    3,
		"Uninstalling": 4,
	}
)

func (x InstallState) Enum() *InstallState {
	p := new(InstallState)
	*p = x
	return p
}

func (x InstallState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallState) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (InstallState) Type() protoreflect.EnumType {
	return &file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_enumTypes[0]
}

func (x InstallState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallState.Descriptor instead.
func (InstallState) EnumDescriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

type InstallStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         InstallState           `protobuf:"varint,1,opt,name=state,proto3,enum=orchestrator.InstallState" json:"state,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStatus) Reset() {
	*x = InstallStatus{}
	mi := &file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStatus) ProtoMessage() {}

func (x *InstallStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStatus.ProtoReflect.Descriptor instead.
func (*InstallStatus) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *InstallStatus) GetState() InstallState {
	if x != nil {
		return x.State
	}
	return InstallState_Unknown
}

func (x *InstallStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"Mgithub.com/rancher/opni/plugins/topology/apis/orchestrator/orchestrator.proto\x12\forchestrator\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15google/api/http.proto\x1a\x1cgoogle/api/annotations.proto\x1a3github.com/rancher/opni/pkg/apis/core/v1/core.proto\"\xdf\x01\n" +
	"\rInstallStatus\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.orchestrator.InstallStateR\x05state\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).orchestrator.InstallStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\\\n" +
	"\fInstallState\x12\v\n" +
	"\aUnknown\x10\x00\x12\x10\n" +
	"\fNotInstalled\x10\x01\x12\f\n" +
	"\bUpdating\x10\x02\x12\r\n" +
	"\tInstalled\x10\x03\x12\x10\n" +
	"\fUninstalling\x10\x042x\n" +
	"\x14TopologyOrchestrator\x12`\n" +
	"\x10GetClusterStatus\x12\x16.google.protobuf.Empty\x1a\x1b.orchestrator.InstallStatus\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/cluster/statusB<Z:github.com/rancher/opni/plugins/topology/apis/orchestratorb\x06proto3"

var (
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDescData
}

var file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_goTypes = []any{
	(InstallState)(0),     // 0: orchestrator.InstallState
	(*InstallStatus)(nil), // 1: orchestrator.InstallStatus
	nil,                   // 2: orchestrator.InstallStatus.MetadataEntry
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.InstallStatus.state:type_name -> orchestrator.InstallState
	2, // 1: orchestrator.InstallStatus.metadata:type_name -> orchestrator.InstallStatus.MetadataEntry
	3, // 2: orchestrator.TopologyOrchestrator.GetClusterStatus:input_type -> google.protobuf.Empty
	1, // 3: orchestrator.TopologyOrchestrator.GetClusterStatus:output_type -> orchestrator.InstallStatus
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_init()
}
func file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_init() {
	if File_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_depIdxs,
		EnumInfos:         file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_enumTypes,
		MessageInfos:      file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto = out.File
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_goTypes = nil
	file_github_com_rancher_opni_plugins_topology_apis_orchestrator_orchestrator_proto_depIdxs = nil
}
