// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/pkg/apis/alerting/v1/sidecar.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // allows for having multiple configs
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConfigRequest) Reset() {
	*x = PutConfigRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConfigRequest) ProtoMessage() {}

func (x *PutConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConfigRequest.ProtoReflect.Descriptor instead.
func (*PutConfigRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *PutConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutConfigRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type SyncerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ready          bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Healthy        bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	SyncInProgress bool                   `protobuf:"varint,3,opt,name=syncInProgress,proto3" json:"syncInProgress,omitempty"`
	LastSynced     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastSynced,proto3" json:"lastSynced,omitempty"`
	ServerConfig   *SyncerConfig          `protobuf:"bytes,5,opt,name=serverConfig,proto3" json:"serverConfig,omitempty"`
	Configs        map[string]string      `protobuf:"bytes,6,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncerStatus) Reset() {
	*x = SyncerStatus{}
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncerStatus) ProtoMessage() {}

func (x *SyncerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncerStatus.ProtoReflect.Descriptor instead.
func (*SyncerStatus) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *SyncerStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *SyncerStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *SyncerStatus) GetSyncInProgress() bool {
	if x != nil {
		return x.SyncInProgress
	}
	return false
}

func (x *SyncerStatus) GetLastSynced() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSynced
	}
	return nil
}

func (x *SyncerStatus) GetServerConfig() *SyncerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

func (x *SyncerStatus) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

type SyncerConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GatewayJoinAddress     string                 `protobuf:"bytes,1,opt,name=gatewayJoinAddress,proto3" json:"gatewayJoinAddress,omitempty"`
	AlertmanagerConfigPath string                 `protobuf:"bytes,2,opt,name=alertmanagerConfigPath,proto3" json:"alertmanagerConfigPath,omitempty"`
	AlertmanagerAddress    string                 `protobuf:"bytes,3,opt,name=alertmanagerAddress,proto3" json:"alertmanagerAddress,omitempty"`
	ListenAddress          string                 `protobuf:"bytes,4,opt,name=listenAddress,proto3" json:"listenAddress,omitempty"`
	HookListenAddress      string                 `protobuf:"bytes,5,opt,name=hookListenAddress,proto3" json:"hookListenAddress,omitempty"`
	PprofPort              int64                  `protobuf:"varint,6,opt,name=pprofPort,proto3" json:"pprofPort,omitempty"`
	ProfileBlockRate       int64                  `protobuf:"varint,7,opt,name=profileBlockRate,proto3" json:"profileBlockRate,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncerConfig) Reset() {
	*x = SyncerConfig{}
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncerConfig) ProtoMessage() {}

func (x *SyncerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncerConfig.ProtoReflect.Descriptor instead.
func (*SyncerConfig) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *SyncerConfig) GetGatewayJoinAddress() string {
	if x != nil {
		return x.GatewayJoinAddress
	}
	return ""
}

func (x *SyncerConfig) GetAlertmanagerConfigPath() string {
	if x != nil {
		return x.AlertmanagerConfigPath
	}
	return ""
}

func (x *SyncerConfig) GetAlertmanagerAddress() string {
	if x != nil {
		return x.AlertmanagerAddress
	}
	return ""
}

func (x *SyncerConfig) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *SyncerConfig) GetHookListenAddress() string {
	if x != nil {
		return x.HookListenAddress
	}
	return ""
}

func (x *SyncerConfig) GetPprofPort() int64 {
	if x != nil {
		return x.PprofPort
	}
	return 0
}

func (x *SyncerConfig) GetProfileBlockRate() int64 {
	if x != nil {
		return x.ProfileBlockRate
	}
	return 0
}

var File_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDesc = "" +
	"\n" +
	":github.com/rancher/opni/pkg/apis/alerting/v1/sidecar.proto\x12\balerting\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15google/api/http.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x10PutConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"\xd9\x02\n" +
	"\fSyncerStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12&\n" +
	"\x0esyncInProgress\x18\x03 \x01(\bR\x0esyncInProgress\x12:\n" +
	"\n" +
	"lastSynced\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSynced\x12:\n" +
	"\fserverConfig\x18\x05 \x01(\v2\x16.alerting.SyncerConfigR\fserverConfig\x12=\n" +
	"\aconfigs\x18\x06 \x03(\v2#.alerting.SyncerStatus.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\fSyncerConfig\x12.\n" +
	"\x12gatewayJoinAddress\x18\x01 \x01(\tR\x12gatewayJoinAddress\x126\n" +
	"\x16alertmanagerConfigPath\x18\x02 \x01(\tR\x16alertmanagerConfigPath\x120\n" +
	"\x13alertmanagerAddress\x18\x03 \x01(\tR\x13alertmanagerAddress\x12$\n" +
	"\rlistenAddress\x18\x04 \x01(\tR\rlistenAddress\x12,\n" +
	"\x11hookListenAddress\x18\x05 \x01(\tR\x11hookListenAddress\x12\x1c\n" +
	"\tpprofPort\x18\x06 \x01(\x03R\tpprofPort\x12*\n" +
	"\x10profileBlockRate\x18\a \x01(\x03R\x10profileBlockRate2\xac\x02\n" +
	"\x06Syncer\x12A\n" +
	"\tPutConfig\x12\x1a.alerting.PutConfigRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\x05Ready\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/ready\x12K\n" +
	"\aHealthy\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthy\x12I\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x16.alerting.SyncerStatus\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/statusB.Z,github.com/rancher/opni/pkg/apis/alerting/v1b\x06proto3"

var (
	file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescData []byte
)

func file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDescData
}

var file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_goTypes = []any{
	(*PutConfigRequest)(nil),      // 0: alerting.PutConfigRequest
	(*SyncerStatus)(nil),          // 1: alerting.SyncerStatus
	(*SyncerConfig)(nil),          // 2: alerting.SyncerConfig
	nil,                           // 3: alerting.SyncerStatus.ConfigsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_depIdxs = []int32{
	4, // 0: alerting.SyncerStatus.lastSynced:type_name -> google.protobuf.Timestamp
	2, // 1: alerting.SyncerStatus.serverConfig:type_name -> alerting.SyncerConfig
	3, // 2: alerting.SyncerStatus.configs:type_name -> alerting.SyncerStatus.ConfigsEntry
	0, // 3: alerting.Syncer.PutConfig:input_type -> alerting.PutConfigRequest
	5, // 4: alerting.Syncer.Ready:input_type -> google.protobuf.Empty
	5, // 5: alerting.Syncer.Healthy:input_type -> google.protobuf.Empty
	5, // 6: alerting.Syncer.Status:input_type -> google.protobuf.Empty
	5, // 7: alerting.Syncer.PutConfig:output_type -> google.protobuf.Empty
	5, // 8: alerting.Syncer.Ready:output_type -> google.protobuf.Empty
	5, // 9: alerting.Syncer.Healthy:output_type -> google.protobuf.Empty
	1, // 10: alerting.Syncer.Status:output_type -> alerting.SyncerStatus
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_init() }
func file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_init() {
	if File_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto = out.File
	file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_goTypes = nil
	file_github_com_rancher_opni_pkg_apis_alerting_v1_sidecar_proto_depIdxs = nil
}
