// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/plugins/topology/apis/representation/representation.proto

package representation

import (
	v1 "github.com/rancher/opni/pkg/apis/core/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphRepr int32

const (
	GraphRepr_None         GraphRepr = 0
	GraphRepr_KubectlGraph GraphRepr = 1
)

// Enum value maps for GraphRepr.
var (
	GraphRepr_name = map[int32]string{
		0: "None",
		1: "KubectlGraph",
	}
	GraphRepr_value = map[string]int32{
		"None":         0,
		"KubectlGraph": 1,
	}
)

func (x GraphRepr) Enum() *GraphRepr {
	p := new(GraphRepr)
	*p = x
	return p
}

func (x GraphRepr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphRepr) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_enumTypes[0].Descriptor()
}

func (GraphRepr) Type() protoreflect.EnumType {
	return &file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_enumTypes[0]
}

func (x GraphRepr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphRepr.Descriptor instead.
func (GraphRepr) EnumDescriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescGZIP(), []int{0}
}

type TopologyGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.Reference          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Repr          GraphRepr              `protobuf:"varint,3,opt,name=repr,proto3,enum=representation.GraphRepr" json:"repr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyGraph) Reset() {
	*x = TopologyGraph{}
	mi := &file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyGraph) ProtoMessage() {}

func (x *TopologyGraph) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyGraph.ProtoReflect.Descriptor instead.
func (*TopologyGraph) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyGraph) GetId() *v1.Reference {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TopologyGraph) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TopologyGraph) GetRepr() GraphRepr {
	if x != nil {
		return x.Repr
	}
	return GraphRepr_None
}

type DOTRepresentation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawDotFormat  string                 `protobuf:"bytes,1,opt,name=rawDotFormat,proto3" json:"rawDotFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DOTRepresentation) Reset() {
	*x = DOTRepresentation{}
	mi := &file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DOTRepresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DOTRepresentation) ProtoMessage() {}

func (x *DOTRepresentation) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DOTRepresentation.ProtoReflect.Descriptor instead.
func (*DOTRepresentation) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescGZIP(), []int{1}
}

func (x *DOTRepresentation) GetRawDotFormat() string {
	if x != nil {
		return x.RawDotFormat
	}
	return ""
}

var File_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDesc = "" +
	"\n" +
	"Qgithub.com/rancher/opni/plugins/topology/apis/representation/representation.proto\x12\x0erepresentation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15google/api/http.proto\x1a\x1cgoogle/api/annotations.proto\x1a3github.com/rancher/opni/pkg/apis/core/v1/core.proto\"s\n" +
	"\rTopologyGraph\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.core.ReferenceR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12-\n" +
	"\x04repr\x18\x03 \x01(\x0e2\x19.representation.GraphReprR\x04repr\"7\n" +
	"\x11DOTRepresentation\x12\"\n" +
	"\frawDotFormat\x18\x01 \x01(\tR\frawDotFormat*'\n" +
	"\tGraphRepr\x12\b\n" +
	"\x04None\x10\x00\x12\x10\n" +
	"\fKubectlGraph\x10\x012\xb6\x01\n" +
	"\x16TopologyRepresentation\x12<\n" +
	"\bGetGraph\x12\x0f.core.Reference\x1a\x1d.representation.TopologyGraph\"\x00\x12^\n" +
	"\vRenderGraph\x12\x0f.core.Reference\x1a!.representation.DOTRepresentation\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/topology/renderB>Z<github.com/rancher/opni/plugins/topology/apis/representationb\x06proto3"

var (
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescData []byte
)

func file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDescData
}

var file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_goTypes = []any{
	(GraphRepr)(0),            // 0: representation.GraphRepr
	(*TopologyGraph)(nil),     // 1: representation.TopologyGraph
	(*DOTRepresentation)(nil), // 2: representation.DOTRepresentation
	(*v1.Reference)(nil),      // 3: core.Reference
}
var file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_depIdxs = []int32{
	3, // 0: representation.TopologyGraph.id:type_name -> core.Reference
	0, // 1: representation.TopologyGraph.repr:type_name -> representation.GraphRepr
	3, // 2: representation.TopologyRepresentation.GetGraph:input_type -> core.Reference
	3, // 3: representation.TopologyRepresentation.RenderGraph:input_type -> core.Reference
	1, // 4: representation.TopologyRepresentation.GetGraph:output_type -> representation.TopologyGraph
	2, // 5: representation.TopologyRepresentation.RenderGraph:output_type -> representation.DOTRepresentation
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_init()
}
func file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_init() {
	if File_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDesc), len(file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_depIdxs,
		EnumInfos:         file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_enumTypes,
		MessageInfos:      file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto = out.File
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_goTypes = nil
	file_github_com_rancher_opni_plugins_topology_apis_representation_representation_proto_depIdxs = nil
}
