// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: github.com/rancher/opni/plugins/alerting/apis/alertops/alertops.proto

package alertops

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertingAdmin_GetClusterConfiguration_FullMethodName = "/alerting.ops.AlertingAdmin/GetClusterConfiguration"
	AlertingAdmin_ConfigureCluster_FullMethodName        = "/alerting.ops.AlertingAdmin/ConfigureCluster"
	AlertingAdmin_GetClusterStatus_FullMethodName        = "/alerting.ops.AlertingAdmin/GetClusterStatus"
	AlertingAdmin_InstallCluster_FullMethodName          = "/alerting.ops.AlertingAdmin/InstallCluster"
	AlertingAdmin_UninstallCluster_FullMethodName        = "/alerting.ops.AlertingAdmin/UninstallCluster"
	AlertingAdmin_Info_FullMethodName                    = "/alerting.ops.AlertingAdmin/Info"
)

// AlertingAdminClient is the client API for AlertingAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The AlertingAdmin service controls meta-operations for
// deploying, connecting & configuring AlertManager in the upstream environment
type AlertingAdminClient interface {
	GetClusterConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterConfiguration, error)
	// Install/Uninstall the alerting cluster by setting enabled=true/false
	ConfigureCluster(ctx context.Context, in *ClusterConfiguration, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InstallStatus, error)
	InstallCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UninstallCluster(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ComponentInfo, error)
}

type alertingAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertingAdminClient(cc grpc.ClientConnInterface) AlertingAdminClient {
	return &alertingAdminClient{cc}
}

func (c *alertingAdminClient) GetClusterConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterConfiguration)
	err := c.cc.Invoke(ctx, AlertingAdmin_GetClusterConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertingAdminClient) ConfigureCluster(ctx context.Context, in *ClusterConfiguration, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlertingAdmin_ConfigureCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertingAdminClient) GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InstallStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallStatus)
	err := c.cc.Invoke(ctx, AlertingAdmin_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertingAdminClient) InstallCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlertingAdmin_InstallCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertingAdminClient) UninstallCluster(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlertingAdmin_UninstallCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertingAdminClient) Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ComponentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentInfo)
	err := c.cc.Invoke(ctx, AlertingAdmin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertingAdminServer is the server API for AlertingAdmin service.
// All implementations should embed UnimplementedAlertingAdminServer
// for forward compatibility.
//
// The AlertingAdmin service controls meta-operations for
// deploying, connecting & configuring AlertManager in the upstream environment
type AlertingAdminServer interface {
	GetClusterConfiguration(context.Context, *emptypb.Empty) (*ClusterConfiguration, error)
	// Install/Uninstall the alerting cluster by setting enabled=true/false
	ConfigureCluster(context.Context, *ClusterConfiguration) (*emptypb.Empty, error)
	GetClusterStatus(context.Context, *emptypb.Empty) (*InstallStatus, error)
	InstallCluster(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	UninstallCluster(context.Context, *UninstallRequest) (*emptypb.Empty, error)
	Info(context.Context, *emptypb.Empty) (*ComponentInfo, error)
}

// UnimplementedAlertingAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertingAdminServer struct{}

func (UnimplementedAlertingAdminServer) GetClusterConfiguration(context.Context, *emptypb.Empty) (*ClusterConfiguration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterConfiguration not implemented")
}
func (UnimplementedAlertingAdminServer) ConfigureCluster(context.Context, *ClusterConfiguration) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureCluster not implemented")
}
func (UnimplementedAlertingAdminServer) GetClusterStatus(context.Context, *emptypb.Empty) (*InstallStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedAlertingAdminServer) InstallCluster(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallCluster not implemented")
}
func (UnimplementedAlertingAdminServer) UninstallCluster(context.Context, *UninstallRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallCluster not implemented")
}
func (UnimplementedAlertingAdminServer) Info(context.Context, *emptypb.Empty) (*ComponentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAlertingAdminServer) testEmbeddedByValue() {}

// UnsafeAlertingAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertingAdminServer will
// result in compilation errors.
type UnsafeAlertingAdminServer interface {
	mustEmbedUnimplementedAlertingAdminServer()
}

func RegisterAlertingAdminServer(s grpc.ServiceRegistrar, srv AlertingAdminServer) {
	// If the following call panics, it indicates UnimplementedAlertingAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertingAdmin_ServiceDesc, srv)
}

func _AlertingAdmin_GetClusterConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).GetClusterConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_GetClusterConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).GetClusterConfiguration(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertingAdmin_ConfigureCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).ConfigureCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_ConfigureCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).ConfigureCluster(ctx, req.(*ClusterConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertingAdmin_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).GetClusterStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertingAdmin_InstallCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).InstallCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_InstallCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).InstallCluster(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertingAdmin_UninstallCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).UninstallCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_UninstallCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).UninstallCluster(ctx, req.(*UninstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertingAdmin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertingAdminServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertingAdmin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertingAdminServer).Info(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertingAdmin_ServiceDesc is the grpc.ServiceDesc for AlertingAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertingAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerting.ops.AlertingAdmin",
	HandlerType: (*AlertingAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterConfiguration",
			Handler:    _AlertingAdmin_GetClusterConfiguration_Handler,
		},
		{
			MethodName: "ConfigureCluster",
			Handler:    _AlertingAdmin_ConfigureCluster_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _AlertingAdmin_GetClusterStatus_Handler,
		},
		{
			MethodName: "InstallCluster",
			Handler:    _AlertingAdmin_InstallCluster_Handler,
		},
		{
			MethodName: "UninstallCluster",
			Handler:    _AlertingAdmin_UninstallCluster_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _AlertingAdmin_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/rancher/opni/plugins/alerting/apis/alertops/alertops.proto",
}

const (
	AdminInfo_SyncInfo_FullMethodName = "/alerting.ops.AdminInfo/SyncInfo"
)

// AdminInfoClient is the client API for AdminInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminInfoClient interface {
	SyncInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminInfoClient(cc grpc.ClientConnInterface) AdminInfoClient {
	return &adminInfoClient{cc}
}

func (c *adminInfoClient) SyncInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminInfo_SyncInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminInfoServer is the server API for AdminInfo service.
// All implementations should embed UnimplementedAdminInfoServer
// for forward compatibility.
type AdminInfoServer interface {
	SyncInfo(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedAdminInfoServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminInfoServer struct{}

func (UnimplementedAdminInfoServer) SyncInfo(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncInfo not implemented")
}
func (UnimplementedAdminInfoServer) testEmbeddedByValue() {}

// UnsafeAdminInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminInfoServer will
// result in compilation errors.
type UnsafeAdminInfoServer interface {
	mustEmbedUnimplementedAdminInfoServer()
}

func RegisterAdminInfoServer(s grpc.ServiceRegistrar, srv AdminInfoServer) {
	// If the following call panics, it indicates UnimplementedAdminInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminInfo_ServiceDesc, srv)
}

func _AdminInfo_SyncInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInfoServer).SyncInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInfo_SyncInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInfoServer).SyncInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminInfo_ServiceDesc is the grpc.ServiceDesc for AdminInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerting.ops.AdminInfo",
	HandlerType: (*AdminInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncInfo",
			Handler:    _AdminInfo_SyncInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/rancher/opni/plugins/alerting/apis/alertops/alertops.proto",
}

const (
	ConfigReconciler_SyncConfig_FullMethodName = "/alerting.ops.ConfigReconciler/SyncConfig"
)

// ConfigReconcilerClient is the client API for ConfigReconciler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigReconcilerClient interface {
	SyncConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectInfo, SyncRequest], error)
}

type configReconcilerClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigReconcilerClient(cc grpc.ClientConnInterface) ConfigReconcilerClient {
	return &configReconcilerClient{cc}
}

func (c *configReconcilerClient) SyncConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectInfo, SyncRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigReconciler_ServiceDesc.Streams[0], ConfigReconciler_SyncConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectInfo, SyncRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigReconciler_SyncConfigClient = grpc.BidiStreamingClient[ConnectInfo, SyncRequest]

// ConfigReconcilerServer is the server API for ConfigReconciler service.
// All implementations should embed UnimplementedConfigReconcilerServer
// for forward compatibility.
type ConfigReconcilerServer interface {
	SyncConfig(grpc.BidiStreamingServer[ConnectInfo, SyncRequest]) error
}

// UnimplementedConfigReconcilerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigReconcilerServer struct{}

func (UnimplementedConfigReconcilerServer) SyncConfig(grpc.BidiStreamingServer[ConnectInfo, SyncRequest]) error {
	return status.Error(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedConfigReconcilerServer) testEmbeddedByValue() {}

// UnsafeConfigReconcilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigReconcilerServer will
// result in compilation errors.
type UnsafeConfigReconcilerServer interface {
	mustEmbedUnimplementedConfigReconcilerServer()
}

func RegisterConfigReconcilerServer(s grpc.ServiceRegistrar, srv ConfigReconcilerServer) {
	// If the following call panics, it indicates UnimplementedConfigReconcilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigReconciler_ServiceDesc, srv)
}

func _ConfigReconciler_SyncConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigReconcilerServer).SyncConfig(&grpc.GenericServerStream[ConnectInfo, SyncRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigReconciler_SyncConfigServer = grpc.BidiStreamingServer[ConnectInfo, SyncRequest]

// ConfigReconciler_ServiceDesc is the grpc.ServiceDesc for ConfigReconciler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigReconciler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerting.ops.ConfigReconciler",
	HandlerType: (*ConfigReconcilerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncConfig",
			Handler:       _ConfigReconciler_SyncConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/rancher/opni/plugins/alerting/apis/alertops/alertops.proto",
}
