// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/plugins/metrics/apis/node/sync.proto

package node

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CurrentConfig *MetricsCapabilityStatus `protobuf:"bytes,1,opt,name=currentConfig,proto3" json:"currentConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetCurrentConfig() *MetricsCapabilityStatus {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ConfigStatus  ConfigStatus             `protobuf:"varint,1,opt,name=configStatus,proto3,enum=node.metrics.config.ConfigStatus" json:"configStatus,omitempty"`
	UpdatedConfig *MetricsCapabilityStatus `protobuf:"bytes,2,opt,name=updatedConfig,proto3" json:"updatedConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetConfigStatus() ConfigStatus {
	if x != nil {
		return x.ConfigStatus
	}
	return ConfigStatus_Unknown
}

func (x *SyncResponse) GetUpdatedConfig() *MetricsCapabilityStatus {
	if x != nil {
		return x.UpdatedConfig
	}
	return nil
}

var File_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDesc = "" +
	"\n" +
	"<github.com/rancher/opni/plugins/metrics/apis/node/sync.proto\x12\fnode.metrics\x1a\x1bbuf/validate/validate.proto\x1a>github.com/rancher/opni/plugins/metrics/apis/node/config.proto\"i\n" +
	"\vSyncRequest\x12Z\n" +
	"\rcurrentConfig\x18\x01 \x01(\v2,.node.metrics.config.MetricsCapabilityStatusB\x06\xbaH\x03\xc8\x01\x01R\rcurrentConfig\"\xa9\x01\n" +
	"\fSyncResponse\x12E\n" +
	"\fconfigStatus\x18\x01 \x01(\x0e2!.node.metrics.config.ConfigStatusR\fconfigStatus\x12R\n" +
	"\rupdatedConfig\x18\x02 \x01(\v2,.node.metrics.config.MetricsCapabilityStatusR\rupdatedConfig2V\n" +
	"\x15NodeMetricsCapability\x12=\n" +
	"\x04Sync\x12\x19.node.metrics.SyncRequest\x1a\x1a.node.metrics.SyncResponseB3Z1github.com/rancher/opni/plugins/metrics/apis/nodeb\x06proto3"

var (
	file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescData []byte
)

func file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDesc), len(file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDescData
}

var file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_goTypes = []any{
	(*SyncRequest)(nil),             // 0: node.metrics.SyncRequest
	(*SyncResponse)(nil),            // 1: node.metrics.SyncResponse
	(*MetricsCapabilityStatus)(nil), // 2: node.metrics.config.MetricsCapabilityStatus
	(ConfigStatus)(0),               // 3: node.metrics.config.ConfigStatus
}
var file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_depIdxs = []int32{
	2, // 0: node.metrics.SyncRequest.currentConfig:type_name -> node.metrics.config.MetricsCapabilityStatus
	3, // 1: node.metrics.SyncResponse.configStatus:type_name -> node.metrics.config.ConfigStatus
	2, // 2: node.metrics.SyncResponse.updatedConfig:type_name -> node.metrics.config.MetricsCapabilityStatus
	0, // 3: node.metrics.NodeMetricsCapability.Sync:input_type -> node.metrics.SyncRequest
	1, // 4: node.metrics.NodeMetricsCapability.Sync:output_type -> node.metrics.SyncResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_init() }
func file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_init() {
	if File_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto != nil {
		return
	}
	file_github_com_rancher_opni_plugins_metrics_apis_node_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDesc), len(file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto = out.File
	file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_goTypes = nil
	file_github_com_rancher_opni_plugins_metrics_apis_node_sync_proto_depIdxs = nil
}
