// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/pkg/test/testgrpc/alerting.test.proto

package testgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSecret) Reset() {
	*x = TestSecret{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSecret) ProtoMessage() {}

func (x *TestSecret) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSecret.ProtoReflect.Descriptor instead.
func (*TestSecret) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestSecret) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TestSecret) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDesc = "" +
	"\n" +
	"=github.com/rancher/opni/pkg/test/testgrpc/alerting.test.proto\"D\n" +
	"\n" +
	"TestSecret\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB+Z)github.com/rancher/opni/pkg/test/testgrpcb\x06proto3"

var (
	file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescData []byte
)

func file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDesc), len(file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDescData
}

var file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_goTypes = []any{
	(*TestSecret)(nil), // 0: TestSecret
}
var file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_init() }
func file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_init() {
	if File_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDesc), len(file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto = out.File
	file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_goTypes = nil
	file_github_com_rancher_opni_pkg_test_testgrpc_alerting_test_proto_depIdxs = nil
}
