// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/pkg/test/testgrpc/cached.proto

package testgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       bool                   `protobuf:"varint,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

// ObjectReference must implement the `CacheKeyer` interface
type ObjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ObjectReference     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectList) Reset() {
	*x = ObjectList{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectList) ProtoMessage() {}

func (x *ObjectList) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectList.ProtoReflect.Descriptor instead.
func (*ObjectList) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectList) GetItems() []*ObjectReference {
	if x != nil {
		return x.Items
	}
	return nil
}

type IncrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{3}
}

func (x *IncrementRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type IncrementObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ObjectReference       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementObjectRequest) Reset() {
	*x = IncrementObjectRequest{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementObjectRequest) ProtoMessage() {}

func (x *IncrementObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementObjectRequest.ProtoReflect.Descriptor instead.
func (*IncrementObjectRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementObjectRequest) GetId() *ObjectReference {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IncrementObjectRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_github_com_rancher_opni_pkg_test_testgrpc_cached_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDesc = "" +
	"\n" +
	"6github.com/rancher/opni/pkg/test/testgrpc/cached.proto\x12\x0ftestgrpc.cached\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x0eRefreshRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\bR\arefresh\"!\n" +
	"\x0fObjectReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\n" +
	"ObjectList\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .testgrpc.cached.ObjectReferenceR\x05items\"(\n" +
	"\x10IncrementRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"`\n" +
	"\x16IncrementObjectRequest\x120\n" +
	"\x02id\x18\x01 \x01(\v2 .testgrpc.cached.ObjectReferenceR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\x1d\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value2\xe6\x01\n" +
	"\rSimpleService\x12F\n" +
	"\tIncrement\x12!.testgrpc.cached.IncrementRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bGetValue\x12\x16.google.protobuf.Empty\x1a\x16.testgrpc.cached.Value\x12Q\n" +
	"\x1fGetValueWithForcedClientCaching\x12\x16.google.protobuf.Empty\x1a\x16.testgrpc.cached.Value2\xec\x01\n" +
	"\rObjectService\x12R\n" +
	"\x0fIncrementObject\x12'.testgrpc.cached.IncrementObjectRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eGetObjectValue\x12 .testgrpc.cached.ObjectReference\x1a\x16.testgrpc.cached.Value\x12;\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1b.testgrpc.cached.ObjectList2\xe3\x01\n" +
	"\x11AggregatorService\x12I\n" +
	"\fIncrementAll\x12!.testgrpc.cached.IncrementRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x16.testgrpc.cached.Value\x12I\n" +
	"\x17GetAllWithNestedCaching\x12\x16.google.protobuf.Empty\x1a\x16.testgrpc.cached.ValueB+Z)github.com/rancher/opni/pkg/test/testgrpcb\x06proto3"

var (
	file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescData []byte
)

func file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDesc), len(file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDescData
}

var file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_goTypes = []any{
	(*RefreshRequest)(nil),         // 0: testgrpc.cached.RefreshRequest
	(*ObjectReference)(nil),        // 1: testgrpc.cached.ObjectReference
	(*ObjectList)(nil),             // 2: testgrpc.cached.ObjectList
	(*IncrementRequest)(nil),       // 3: testgrpc.cached.IncrementRequest
	(*IncrementObjectRequest)(nil), // 4: testgrpc.cached.IncrementObjectRequest
	(*Value)(nil),                  // 5: testgrpc.cached.Value
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_depIdxs = []int32{
	1,  // 0: testgrpc.cached.ObjectList.items:type_name -> testgrpc.cached.ObjectReference
	1,  // 1: testgrpc.cached.IncrementObjectRequest.id:type_name -> testgrpc.cached.ObjectReference
	3,  // 2: testgrpc.cached.SimpleService.Increment:input_type -> testgrpc.cached.IncrementRequest
	6,  // 3: testgrpc.cached.SimpleService.GetValue:input_type -> google.protobuf.Empty
	6,  // 4: testgrpc.cached.SimpleService.GetValueWithForcedClientCaching:input_type -> google.protobuf.Empty
	4,  // 5: testgrpc.cached.ObjectService.IncrementObject:input_type -> testgrpc.cached.IncrementObjectRequest
	1,  // 6: testgrpc.cached.ObjectService.GetObjectValue:input_type -> testgrpc.cached.ObjectReference
	6,  // 7: testgrpc.cached.ObjectService.List:input_type -> google.protobuf.Empty
	3,  // 8: testgrpc.cached.AggregatorService.IncrementAll:input_type -> testgrpc.cached.IncrementRequest
	6,  // 9: testgrpc.cached.AggregatorService.GetAll:input_type -> google.protobuf.Empty
	6,  // 10: testgrpc.cached.AggregatorService.GetAllWithNestedCaching:input_type -> google.protobuf.Empty
	6,  // 11: testgrpc.cached.SimpleService.Increment:output_type -> google.protobuf.Empty
	5,  // 12: testgrpc.cached.SimpleService.GetValue:output_type -> testgrpc.cached.Value
	5,  // 13: testgrpc.cached.SimpleService.GetValueWithForcedClientCaching:output_type -> testgrpc.cached.Value
	6,  // 14: testgrpc.cached.ObjectService.IncrementObject:output_type -> google.protobuf.Empty
	5,  // 15: testgrpc.cached.ObjectService.GetObjectValue:output_type -> testgrpc.cached.Value
	2,  // 16: testgrpc.cached.ObjectService.List:output_type -> testgrpc.cached.ObjectList
	6,  // 17: testgrpc.cached.AggregatorService.IncrementAll:output_type -> google.protobuf.Empty
	5,  // 18: testgrpc.cached.AggregatorService.GetAll:output_type -> testgrpc.cached.Value
	5,  // 19: testgrpc.cached.AggregatorService.GetAllWithNestedCaching:output_type -> testgrpc.cached.Value
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_init() }
func file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_init() {
	if File_github_com_rancher_opni_pkg_test_testgrpc_cached_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDesc), len(file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_pkg_test_testgrpc_cached_proto = out.File
	file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_goTypes = nil
	file_github_com_rancher_opni_pkg_test_testgrpc_cached_proto_depIdxs = nil
}
