// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/pkg/apis/bootstrap/v1/bootstrap.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapJoinRequest) Reset() {
	*x = BootstrapJoinRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapJoinRequest) ProtoMessage() {}

func (x *BootstrapJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapJoinRequest.ProtoReflect.Descriptor instead.
func (*BootstrapJoinRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

type BootstrapJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    map[string][]byte      `protobuf:"bytes,1,rep,name=Signatures,proto3" json:"Signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapJoinResponse) Reset() {
	*x = BootstrapJoinResponse{}
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapJoinResponse) ProtoMessage() {}

func (x *BootstrapJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapJoinResponse.ProtoReflect.Descriptor instead.
func (*BootstrapJoinResponse) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapJoinResponse) GetSignatures() map[string][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type BootstrapAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientPubKey  []byte                 `protobuf:"bytes,2,opt,name=ClientPubKey,proto3" json:"ClientPubKey,omitempty"`
	Capability    string                 `protobuf:"bytes,3,opt,name=Capability,proto3" json:"Capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAuthRequest) Reset() {
	*x = BootstrapAuthRequest{}
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAuthRequest) ProtoMessage() {}

func (x *BootstrapAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAuthRequest.ProtoReflect.Descriptor instead.
func (*BootstrapAuthRequest) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapAuthRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *BootstrapAuthRequest) GetClientPubKey() []byte {
	if x != nil {
		return x.ClientPubKey
	}
	return nil
}

func (x *BootstrapAuthRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type BootstrapAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerPubKey  []byte                 `protobuf:"bytes,1,opt,name=ServerPubKey,proto3" json:"ServerPubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAuthResponse) Reset() {
	*x = BootstrapAuthResponse{}
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAuthResponse) ProtoMessage() {}

func (x *BootstrapAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAuthResponse.ProtoReflect.Descriptor instead.
func (*BootstrapAuthResponse) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapAuthResponse) GetServerPubKey() []byte {
	if x != nil {
		return x.ServerPubKey
	}
	return nil
}

var File_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"=github.com/rancher/opni/pkg/apis/bootstrap/v1/bootstrap.proto\x12\tbootstrap\"\x16\n" +
	"\x14BootstrapJoinRequest\"\xa8\x01\n" +
	"\x15BootstrapJoinResponse\x12P\n" +
	"\n" +
	"Signatures\x18\x01 \x03(\v20.bootstrap.BootstrapJoinResponse.SignaturesEntryR\n" +
	"Signatures\x1a=\n" +
	"\x0fSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"v\n" +
	"\x14BootstrapAuthRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\"\n" +
	"\fClientPubKey\x18\x02 \x01(\fR\fClientPubKey\x12\x1e\n" +
	"\n" +
	"Capability\x18\x03 \x01(\tR\n" +
	"Capability\";\n" +
	"\x15BootstrapAuthResponse\x12\"\n" +
	"\fServerPubKey\x18\x01 \x01(\fR\fServerPubKey2\xa1\x01\n" +
	"\tBootstrap\x12I\n" +
	"\x04Join\x12\x1f.bootstrap.BootstrapJoinRequest\x1a .bootstrap.BootstrapJoinResponse\x12I\n" +
	"\x04Auth\x12\x1f.bootstrap.BootstrapAuthRequest\x1a .bootstrap.BootstrapAuthResponseB/Z-github.com/rancher/opni/pkg/apis/bootstrap/v1b\x06proto3"

var (
	file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescData []byte
)

func file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDescData
}

var file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_goTypes = []any{
	(*BootstrapJoinRequest)(nil),  // 0: bootstrap.BootstrapJoinRequest
	(*BootstrapJoinResponse)(nil), // 1: bootstrap.BootstrapJoinResponse
	(*BootstrapAuthRequest)(nil),  // 2: bootstrap.BootstrapAuthRequest
	(*BootstrapAuthResponse)(nil), // 3: bootstrap.BootstrapAuthResponse
	nil,                           // 4: bootstrap.BootstrapJoinResponse.SignaturesEntry
}
var file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_depIdxs = []int32{
	4, // 0: bootstrap.BootstrapJoinResponse.Signatures:type_name -> bootstrap.BootstrapJoinResponse.SignaturesEntry
	0, // 1: bootstrap.Bootstrap.Join:input_type -> bootstrap.BootstrapJoinRequest
	2, // 2: bootstrap.Bootstrap.Auth:input_type -> bootstrap.BootstrapAuthRequest
	1, // 3: bootstrap.Bootstrap.Join:output_type -> bootstrap.BootstrapJoinResponse
	3, // 4: bootstrap.Bootstrap.Auth:output_type -> bootstrap.BootstrapAuthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_init() }
func file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_init() {
	if File_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDesc), len(file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto = out.File
	file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_goTypes = nil
	file_github_com_rancher_opni_pkg_apis_bootstrap_v1_bootstrap_proto_depIdxs = nil
}
