// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/rancher/opni/plugins/logging/apis/opensearch/opensearch.proto

package opensearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterReference struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizedClusterID string                 `protobuf:"bytes,1,opt,name=AuthorizedClusterID,proto3" json:"AuthorizedClusterID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClusterReference) Reset() {
	*x = ClusterReference{}
	mi := &file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterReference) ProtoMessage() {}

func (x *ClusterReference) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterReference.ProtoReflect.Descriptor instead.
func (*ClusterReference) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterReference) GetAuthorizedClusterID() string {
	if x != nil {
		return x.AuthorizedClusterID
	}
	return ""
}

type OpensearchDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ExternalURL    string                 `protobuf:"bytes,3,opt,name=ExternalURL,proto3" json:"ExternalURL,omitempty"`
	TracingEnabled bool                   `protobuf:"varint,4,opt,name=TracingEnabled,proto3" json:"TracingEnabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpensearchDetails) Reset() {
	*x = OpensearchDetails{}
	mi := &file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpensearchDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpensearchDetails) ProtoMessage() {}

func (x *OpensearchDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpensearchDetails.ProtoReflect.Descriptor instead.
func (*OpensearchDetails) Descriptor() ([]byte, []int) {
	return file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescGZIP(), []int{1}
}

func (x *OpensearchDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpensearchDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OpensearchDetails) GetExternalURL() string {
	if x != nil {
		return x.ExternalURL
	}
	return ""
}

func (x *OpensearchDetails) GetTracingEnabled() bool {
	if x != nil {
		return x.TracingEnabled
	}
	return false
}

var File_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto protoreflect.FileDescriptor

const file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDesc = "" +
	"\n" +
	"Hgithub.com/rancher/opni/plugins/logging/apis/opensearch/opensearch.proto\x12\n" +
	"opensearch\"D\n" +
	"\x10ClusterReference\x120\n" +
	"\x13AuthorizedClusterID\x18\x01 \x01(\tR\x13AuthorizedClusterID\"\x95\x01\n" +
	"\x11OpensearchDetails\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12 \n" +
	"\vExternalURL\x18\x03 \x01(\tR\vExternalURL\x12&\n" +
	"\x0eTracingEnabled\x18\x04 \x01(\bR\x0eTracingEnabled2W\n" +
	"\n" +
	"Opensearch\x12I\n" +
	"\n" +
	"GetDetails\x12\x1c.opensearch.ClusterReference\x1a\x1d.opensearch.OpensearchDetailsB9Z7github.com/rancher/opni/plugins/logging/apis/opensearchb\x06proto3"

var (
	file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescOnce sync.Once
	file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescData []byte
)

func file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescGZIP() []byte {
	file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescOnce.Do(func() {
		file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDesc), len(file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDesc)))
	})
	return file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDescData
}

var file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_goTypes = []any{
	(*ClusterReference)(nil),  // 0: opensearch.ClusterReference
	(*OpensearchDetails)(nil), // 1: opensearch.OpensearchDetails
}
var file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_depIdxs = []int32{
	0, // 0: opensearch.Opensearch.GetDetails:input_type -> opensearch.ClusterReference
	1, // 1: opensearch.Opensearch.GetDetails:output_type -> opensearch.OpensearchDetails
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_init() }
func file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_init() {
	if File_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDesc), len(file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_goTypes,
		DependencyIndexes: file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_depIdxs,
		MessageInfos:      file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_msgTypes,
	}.Build()
	File_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto = out.File
	file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_goTypes = nil
	file_github_com_rancher_opni_plugins_logging_apis_opensearch_opensearch_proto_depIdxs = nil
}
